
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://figccxfcabyiueokmmee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZ2NjeGZjYWJ5aXVlb2ttbWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5Mjc2OTUsImV4cCI6MjA1NzUwMzY5NX0.Um3xlt3RzP0j_W8GKkvGNS5ltJmxjzWD2LTMJHm5Ut8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
